/*
* Proyecto1Reloj.asm
*
* Creado: 2/03/2026 17:06:52
* Autor : Jorge Dieguez
* Descripción: Reloj de alarma
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START

MIN_UNIDADES:	.byte 1
MIN_DECENAS:	.byte 1
HRS_UNIDADES:	.byte 1
HRS_DECENAS:	.byte 1
DIAS_UNIDADES:	.byte 1
DIAS_DECENAS:	.byte 1
HRS_U_MOD:		.byte 1
HRS_D_MOD:		.byte 1
MIN_U_MOD:		.byte 1
MIN_D_MOD:		.byte 1
MES_UNIDADES:	.byte 1
MES_DECENAS:	.byte 1
ESTADO_ANT:		.byte 1
ESTADO_ANT_ALM: .byte 1

DIA:	.byte 1
MES:	.byte 1

MIN_UNIDADES_ALM:       .byte 1
MIN_DECENAS_ALM:       .byte 1
HRS_UNIDADES_ALM:       .byte 1
HRS_DECENAS_ALM:       .byte 1

DISP_ACTUAL:     .byte 1
BANDERAS:        .byte 1
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)
//1B1E

.equ T0VALUE		= 0xB1
.equ T1VALUE		= 0x1B1E
.equ T2VALUE		= 0xF6
.equ MAX_MODOS		= 8
.def MODO			= R19
.def BANDERA_SUMA	= R20
.def BANDERA_RESTA	= R24

.cseg
.org 0x0000
	JMP START

.org PCI1addr
	JMP PC_ISR

.org OVF2addr
	JMP TMR2_ISR

.org OVF1addr
	JMP TMR1_ISR
	
.org OVF0addr
	JMP TMR0_ISR

disp7seg:
	.db 0x40, 0x79, 0x24, 0x30,	0x19, 0x12,	0x02, 0x78, 0x00, 0x10, 0x08, 0x03, 0x46, 0x21, 0x06, 0x0E

START:
/****************************************/
// Configuración de la pila
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16

CLR R16
STS MIN_UNIDADES, R16
STS MIN_DECENAS, R16
STS HRS_UNIDADES, R16
STS HRS_DECENAS, R16
STS DIAS_DECENAS, R16
STS MES_DECENAS, R16

LDI R16, 2
STS HRS_DECENAS_ALM, R16
LDI R16, 3
STS HRS_UNIDADES_ALM, R16
LDI R16, 5
STS MIN_DECENAS_ALM, R16
LDI R16, 9
STS MIN_UNIDADES_ALM, R16

LDI R16, 1
STS DIAS_UNIDADES, R16
STS MES_UNIDADES, R16

/****************************************/
// Configuracion MCU
SETUP:
	//Desactivar TX y DX en D0 y D1
	CLR r16
	STS UCSR0B, r16

	// Prescaler del reloj del sistema
    LDI		R16, (1 << CLKPCE)
	STS		CLKPR, R16 // Permitir el prescaler del sistema
	LDI		R16, (1 << CLKPS2)
	STS		CLKPR, R16 //Poner el prescaler en 16
	
	//Salidas y entradas
		//Puerto D
		LDI		R16, 0xFF // Cargando valor para poner todos los pines como salida
		OUT		DDRD, R16

		// Configuracion para que los display muestren 0 al inicio
			LDI		ZH, HIGH(disp7seg<<1)
			LDI		ZL, LOW(disp7seg<<1)

			LPM		r16, Z
			ORI		R16, 0b10000000
			OUT		PORTD, r16 //Para que muestre 0 inicialmente

		//Puerto C
		LDI R16, 0b00111000 // Para que los pines 3, 4 y 5 sean salidas
		OUT DDRC, R16
		LDI R16, 0b00000111 // Activar Pull-up interno para los pines del 0 al 3
		OUT PORTC, R16

		IN R16, PINC
		STS ESTADO_ANT, R16

		//Puerto B
		LDI R16, 0b00011111 // Valor para activar las salidas del puerto B
		OUT DDRB, R16
		LDI R16, 0b00001111 // Empezar con todos los displays en 0
		OUT PORTB, R16

	//Configurar el Timer 0
	CALL INIT_TIMER0
	LDI R16, 0b00000111
	OUT PORTC, R16
	//Configurar el Timer 1
	CALL INIT_TIMER1

	//Configurar el Timer 2
	CALL INIT_TIMER2

	LDI R16, 0b00000111 // Activar Pull-up interno para los pines del 0 al 3
	OUT PORTC, R16

	//Habilitar interrupciones
		// Pin Change
		LDI R16, (1 << PCIE1)
		STS PCICR, R16 // Habilitando la interrupcion en el PINC

		LDI R16, (1 << PCINT10)|(1 << PCINT9)|(1 << PCINT8)
		STS PCMSK1, R16 // Habilitando los pines del 0 al 2
	
		//Mascara del timer0
		LDI R16, (1 << TOIE0)
		STS TIMSK0, R16 

		//Mascara del timer1
		LDI R16, (1 << TOIE1)
		STS TIMSK1, R16

		//Mascara del timer2
		LDI R16, (1 << TOIE2)
		STS TIMSK2, R16

		//Borrar registros
		CLR MODO
		CLR BANDERA_SUMA
		CLR BANDERA_RESTA
		CLR R1
		CLR R16
		CLR R18
		CLR R21
		CLR R22
		CLR R23
		CLR R25
		CLR R27
		CLR R28
		CLR R29
		IN	R17, PINC
		STS	ESTADO_ANT, R17
		CLR R17
		

	//HABILITAR INTERRUPCIONES GLOBALES
	SEI

/****************************************/
// Loop Infinito
MAIN_LOOP:
	//Verificar bandera del dia
	LDS     R16, BANDERAS
    SBRS    R16, 0
    RJMP    CONTINUAR_MAIN
    CLR		R16
    STS     BANDERAS, R16
    CALL	VERIFICAR_MES

	CONTINUAR_MAIN:
	CPI MODO, 0
	BREQ CONTINUAR_0
	CPI MODO, 1
	BREQ CONTINUAR_1
	CPI MODO, 2
	BREQ CONTINUAR_2
	CPI MODO, 3
	BREQ CONTINUAR_3
	CPI MODO, 4
	BREQ CONTINUAR_4
	CPI MODO, 5
	BREQ CONTINUAR_5
	CPI MODO, 6
	BREQ CONTINUAR_6
	CPI MODO, 7
	BREQ CONTINUAR_7

	CONTINUAR_0:
		RJMP MODO_0
	CONTINUAR_1:
		RJMP MODO_1
	CONTINUAR_2:
		RJMP MODO_2
	CONTINUAR_3:
		RJMP MODO_3
	CONTINUAR_4:
		RJMP MODO_4
	CONTINUAR_5:
		RJMP MODO_5
	CONTINUAR_6:
		RJMP MODO_6
	CONTINUAR_7:
		RJMP MODO_7

	RJMP MAIN_LOOP

	//MODO RELOJ
	MODO_0:
		SBI PORTC, PORTC3
		CBI PORTC, PORTC4
		CBI PORTC, PORTC5

		CALL COMPARAR_ALM

		//Multiplexado del reloj
		CALL	MOSTRAR_UNI_MIN
		SBI		PORTB, PORTB3
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB3

		CALL	MOSTRAR_DEC_MIN
		SBI		PORTB, PORTB2
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB2

		CALL	MOSTRAR_UNI_HRS
		SBI		PORTB, PORTB1
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB1

		CALL	MOSTRAR_DEC_HRS
		SBI		PORTB, PORTB0
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB0

		SIGUE_MOD0:
			CLR BANDERA_SUMA
			CLR BANDERA_RESTA
			RJMP SALIDA

	//MODO FECHA
	MODO_1:
		CBI PORTC, PORTC3
		SBI PORTC, PORTC4
		CBI PORTC, PORTC5

		//Multiplexado de la fecha
		CALL	MOSTRAR_UNI_MES
		SBI		PORTB, PORTB3
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB3

		CALL	MOSTRAR_DEC_MES
		SBI		PORTB, PORTB2
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB2

		CALL	MOSTRAR_UNI_DIA
		SBI		PORTB, PORTB1
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB1

		CALL	MOSTRAR_DEC_DIA
		SBI		PORTB, PORTB0
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB0
		
		RJMP SALIDA

	//CONFIGURACION DE LOS MINUTOS
	MODO_2:
		SBI		PORTC, PORTC3
		CBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M2
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M2

		//Multiplexado de los minutos
		CBI PORTB, PORTB0
		CBI PORTB, PORTB1

		CALL	MOSTRAR_UNI_MIN
		SBI		PORTB, PORTB3
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB3

		CALL	MOSTRAR_DEC_MIN
		SBI		PORTB, PORTB2
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB2

		RJMP SALIDA

	//CONFIGURACION DE LA HORA
	MODO_3:
		SBI		PORTC, PORTC3
		CBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M3
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M3

		//Multiplexado de los minutos
		CBI PORTB, PORTB2
		CBI PORTB, PORTB3

		CALL	MOSTRAR_UNI_HRS
		SBI		PORTB, PORTB1
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB1

		CALL	MOSTRAR_DEC_HRS
		SBI		PORTB, PORTB0
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB0

		RJMP SALIDA


	//CONFIGURACION DEL MES
	MODO_4:
		CBI		PORTC, PORTC3
		SBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M4
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M4

		//MULTIPLEXADO MESES
		CBI PORTB, PORTB0
		CBI PORTB, PORTB1

		CALL	MOSTRAR_UNI_MES
		SBI		PORTB, PORTB3
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB3

		CALL	MOSTRAR_DEC_MES
		SBI		PORTB, PORTB2
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB2

		RJMP SALIDA

	//CONFIGURACION DEL DIA
	MODO_5:
		CBI		PORTC, PORTC3
		SBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M5
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M5

		CBI PORTB, PORTB2
		CBI PORTB, PORTB3

		CALL	MOSTRAR_UNI_DIA
		SBI		PORTB, PORTB1
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB1

		CALL	MOSTRAR_DEC_DIA
		SBI		PORTB, PORTB0
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB0

		STS HRS_DECENAS_ALM, R1
		STS HRS_UNIDADES_ALM, R1
		STS MIN_DECENAS_ALM, R1
		STS MIN_UNIDADES_ALM, R1

		RJMP SALIDA

	//CONFIGURACION DEL MINUTO DE LA ALARMA
	MODO_6:
		SBI		PORTC, PORTC3
		SBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M6
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M6

		//Multiplexado de los minutos
		CBI PORTB, PORTB0
		CBI PORTB, PORTB1

		CALL	MOSTRAR_UNI_MIN_ALM
		SBI		PORTB, PORTB3
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB3

		CALL	MOSTRAR_DEC_MIN_ALM
		SBI		PORTB, PORTB2
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB2

		RJMP SALIDA

	//CONFIGURACION DE LA HORA DE LA ALARMA
	MODO_7:
		SBI		PORTC, PORTC3
		SBI		PORTC, PORTC4
		SBIC	PIND, PIND7
		SBI		PORTC, PORTC5
		SBIS	PIND, PIND7
		CBI		PORTC, PORTC5

		SBRC BANDERA_SUMA, 0
		CALL SUMAR_M7
		SBRC BANDERA_RESTA, 0
		CALL RESTAR_M7

		//Multiplexado de los minutos
		CBI PORTB, PORTB2
		CBI PORTB, PORTB3

		CALL	MOSTRAR_UNI_HRS_ALM
		SBI		PORTB, PORTB1
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB1

		CALL	MOSTRAR_DEC_HRS_ALM
		SBI		PORTB, PORTB0
		OUT		PORTD, R16
		CALL	DELAY
		CBI		PORTB, PORTB0

		RJMP SALIDA

	SALIDA:
		RJMP MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines
INIT_TIMER0:
	PUSH R16

	LDI R16, 0x00 // Valor para timer en modo normal
	STS TCCR0A, R16
	LDI R16, (1 << CS01)|(1 << CS00)// Prescaler
	STS TCCR0B, R16
	LDI R16, T0VALUE // Valor inicial para TCNT
	STS TCNT0, R16

	POP R16
	RET 

INIT_TIMER1: 
	PUSH R16 

	LDI R16, 0x00
	STS TCCR1A, R16 // Poner el timer en modo Normal
	LDI R16, (1 << CS12)|(1 << CS10)
	STS TCCR1B, R16 // Prescaler del reloj
	LDI R16, HIGH(T1VALUE)
	STS TCNT1H, R16 // Cargar valor al TCNT para modo normal
	LDI R16, LOW(T1VALUE)
	STS TCNT1L, R16

	POP R16
	RET 

INIT_TIMER2:
	PUSH R16 

	CLR R16
	STS TCCR2A, R16
	LDI R16, (1 << CS22)|(1 << CS21)
	STS TCCR2B, R16
	LDI R16, T2VALUE
	STS TCNT2, R16

	POP R16
	RET

DELAY:
    LDI R22, 255
	LOOP_DELAY:
		DEC R22
		BRNE LOOP_DELAY
		RET

VERIFICAR_MES:
	LDS R16, MES_UNIDADES
	LDS R17, MES_DECENAS
	CPI	R17, 0
	BREQ PRIMEROS_9_MES
	CPI R16, 0
	BREQ DIAS_31_CALL
	CPI R16, 1
	BREQ DIAS_30
	CPI R16, 2
	BREQ DICIEMBRE_CALL
	RET

DIAS_31_CALL:
	RJMP DIAS_31

DICIEMBRE_CALL:
	RJMP DICIEMBRE
	
PRIMEROS_9_MES:
	CPI R16, 1
	BREQ DIAS_31
	CPI R16, 2
	BREQ DIAS_28_CALL
	CPI R16, 3
	BREQ DIAS_31
	CPI R16, 4
	BREQ DIAS_30 
	CPI R16, 5
	BREQ DIAS_31
	CPI R16, 6
	BREQ DIAS_30
	CPI R16, 7 
	BREQ DIAS_31
	CPI R16, 8
	BREQ DIAS_31
	CPI R16, 9
	BREQ SEPTIEMBRE_CALL
	RET

SEPTIEMBRE_CALL:
	RJMP SEPTIEMBRE

DIAS_28_CALL:
	RJMP DIAS_28

	GUARDAR_DIA:
		STS		DIAS_UNIDADES, R16
		STS		DIAS_DECENAS, R18
		RJMP	SALIDA_MES

	DIAS_30:
		LDS		R16, DIAS_UNIDADES
		INC		R16
		CPI		R16, 1
		BREQ	VERIFICAR_30

		SEGUIR_30:
			CPI		R16, 10
			BRNE	GUARDAR_DIA
			CLR		R16
			STS		DIAS_UNIDADES, R16 
			LDS		R16, DIAS_DECENAS
			INC		R16
			STS		DIAS_DECENAS, R16
			RET
		
		VERIFICAR_30:
			LDS		R18, DIAS_DECENAS
			CPI		R18, 3
			BRNE	SEGUIR_30
			LDS		R16, MES_UNIDADES
			INC		R16
			STS		MES_UNIDADES, R16
			LDI		R16, 1
			STS		DIAS_UNIDADES, R16
			CLR		R16
			STS		DIAS_DECENAS, R16

		RET

	DIAS_31:
		LDS		R16, DIAS_UNIDADES
		INC		R16
		CPI		R16, 2
		BREQ	VERIFICAR_31

		SEGUIR_31:
			CPI		R16, 10
			BRNE	GUARDAR_DIA
			CLR		R16
			STS		DIAS_UNIDADES, R16 
			LDS		R16, DIAS_DECENAS
			INC		R16
			STS		DIAS_DECENAS, R16
			RET
		
		VERIFICAR_31:
			LDS		R18, DIAS_DECENAS
			CPI		R18, 3
			BRNE	SEGUIR_31
			LDS		R16, MES_UNIDADES
			INC		R16
			STS		MES_UNIDADES, R16
			LDI		R16, 1
			STS		DIAS_UNIDADES, R16
			CLR		R16
			STS		DIAS_DECENAS, R16
			RET

	DIAS_28:
		LDS		R16, DIAS_UNIDADES
		INC		R16
		CPI		R16, 9
		BREQ	VERIFICAR_28

		SEGUIR_28:
			CPI		R16, 10
			BRNE	GUARDAR_DIA_CALL
			CLR		R16
			STS		DIAS_UNIDADES, R16 
			LDS		R16, DIAS_DECENAS
			INC		R16
			STS		DIAS_DECENAS, R16
			RET
		
		VERIFICAR_28:
			LDS		R18, DIAS_DECENAS
			CPI		R18, 2
			BRNE	SEGUIR_28
			LDS		R16, MES_UNIDADES
			INC		R16
			STS		MES_UNIDADES, R16
			LDI		R16, 1
			STS		DIAS_UNIDADES, R16
			CLR		R16
			STS		DIAS_DECENAS, R16
			RET

	GUARDAR_DIA_CALL:
		RJMP GUARDAR_DIA

	SEPTIEMBRE:
		LDS		R16, DIAS_UNIDADES
		INC		R16
		CPI		R16, 1
		BREQ	VERIFICAR_30_SEP

		SEGUIR_30_SEP:
			CPI		R16, 10
			BRNE	GUARDAR_DIA_CALL
			CLR		R16
			STS		DIAS_UNIDADES, R16 
			LDS		R16, DIAS_DECENAS
			INC		R16
			STS		DIAS_DECENAS, R16
			RET
		
		VERIFICAR_30_SEP:
			LDS		R18, DIAS_DECENAS
			CPI		R18, 3
			BRNE	SEGUIR_30_SEP
			LDS		R16, MES_UNIDADES
			INC		R16
			STS		MES_UNIDADES, R16
			LDI		R16, 1
			STS		DIAS_UNIDADES, R16
			STS		MES_DECENAS, R16
			CLR		R16
			STS		DIAS_DECENAS, R16 
			STS		MES_UNIDADES, R16

		RET

	DICIEMBRE:
		LDS		R16, DIAS_UNIDADES
		INC		R16
		CPI		R16, 2
		BREQ	VERIFICAR_31_DIC

		SEGUIR_31_DIC:
			CPI		R16, 10
			BRNE	GUARDAR_DIA_CALL
			CLR		R16
			STS		DIAS_UNIDADES, R16 
			LDS		R16, DIAS_DECENAS
			INC		R16
			STS		DIAS_DECENAS, R16
			RET
		
		VERIFICAR_31_DIC:
			LDS		R18, DIAS_DECENAS
			CPI		R18, 3
			BRNE	SEGUIR_31_DIC
			LDS		R16, MES_UNIDADES
			INC		R16
			STS		MES_UNIDADES, R16
			LDI		R16, 1
			STS		DIAS_UNIDADES, R16
			STS		MES_UNIDADES, R16
			CLR		R16
			STS		DIAS_DECENAS, R16
			STS		MES_DECENAS, R16
			RET
	RET
			
SALIDA_MES:
	RET

MOSTRAR_UNI_MIN:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MIN_UNIDADES
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000//Para conservar el bit 7
	OR		R16, R17
	RET

MOSTRAR_DEC_MIN:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MIN_DECENAS
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_UNI_HRS:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, HRS_UNIDADES
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_DEC_HRS:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, HRS_DECENAS
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_UNI_DIA:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, DIAS_UNIDADES
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000//Para conservar el bit 7
	OR		R16, R17
	RET

MOSTRAR_DEC_DIA:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, DIAS_DECENAS
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_UNI_MES:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MES_UNIDADES
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_DEC_MES:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MES_DECENAS
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_UNI_MIN_ALM:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MIN_UNIDADES_ALM
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000//Para conservar el bit 7
	OR		R16, R17
	RET

MOSTRAR_DEC_MIN_ALM:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, MIN_DECENAS_ALM
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

MOSTRAR_UNI_HRS_ALM:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, HRS_UNIDADES_ALM
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000//Para conservar el bit 7
	OR		R16, R17
	RET

MOSTRAR_DEC_HRS_ALM:
	LDI		ZH, HIGH(disp7seg<<1)
	LDI		ZL, LOW(disp7seg<<1)
	LDS		R18, HRS_DECENAS_ALM
	ADD		ZL, R18
	ADC		ZH, R1
	LPM		R17, Z
	IN		R16, PORTD
	ANDI	R16, 0b10000000
	OR		R16, R17
	RET

//Sumar en modo minutos
SUMAR_M2:
	LDS     R26, MIN_UNIDADES
	LDS		R25, MIN_DECENAS 
    INC     R26
	CPI     R26, 10 //Comparar con 10 para aumentar decenas
    BRNE    SALIDA_SM2
	CLR     R26
	STS		MIN_UNIDADES, R26

	INC		R25
	STS		MIN_DECENAS, R25
    CPI     R25, 6 //Comparar con 6 para aumentar la hora
    BRLO    SALIDA_SM2
	CLR     R25
	STS		MIN_DECENAS, R25
	RJMP	SALIDA_SM2

	SALIDA_SM2:
		STS		MIN_UNIDADES, R26
		STS		MIN_DECENAS, R25
		CLR		BANDERA_SUMA
		RET

//Restar en modo minutos
RESTAR_M2:
	LDS R26, MIN_UNIDADES
	LDS  R25, MIN_DECENAS
	CPI	 R26, 0
	BREQ REV_DEC_M2
	DEC  R26
	RJMP SALIDA_RM2
	
	REV_DEC_M2:
		CPI  R25, 0
		BREQ PEDIR_PRESTADO_M2
		LDI R26, 9
		DEC R25
		RJMP SALIDA_RM2
 
	PEDIR_PRESTADO_M2:
		LDI  R26, 9
		LDI  R25, 5
		RJMP SALIDA_RM2

	SALIDA_RM2:
		STS  MIN_UNIDADES, R26
		STS  MIN_DECENAS, R25
		CLR BANDERA_RESTA
		RET

//Sumar en modo horas
SUMAR_M3:
	LDS     R26, HRS_UNIDADES
	LDS		R25, HRS_DECENAS 
    INC     R26
	CPI		R26, 4
	BREQ	CONFIRMAR_AUMENTO_M3
	CPI     R26, 10 //Comparar con 10 para aumentar decenas
    BRNE    SALIDA_SM3
	CLR     R26
	STS		HRS_UNIDADES, R26

	INC		R25
	STS		HRS_DECENAS, R25
	RJMP	SALIDA_SM3

	CONFIRMAR_AUMENTO_M3:
		CPI R25, 2
		BRNE SALIDA_SM3
		CLR R26
		CLR R25

	SALIDA_SM3:
		STS		HRS_UNIDADES, R26
		STS		HRS_DECENAS, R25
		CLR		BANDERA_SUMA
		RET

//Restar en modo horas
RESTAR_M3:
	LDS R26, HRS_UNIDADES
	LDS  R25, HRS_DECENAS
	CPI	 R26, 0
	BREQ REV_DEC_M3
	DEC  R26
	RJMP SALIDA_RM3
	
	REV_DEC_M3:
		CPI  R25, 0
		BREQ PEDIR_PRESTADO_M3
		LDI R26, 9
		DEC R25
		RJMP SALIDA_RM3
 
	PEDIR_PRESTADO_M3:
		LDI  R26, 3
		LDI  R25, 2
		RJMP SALIDA_RM3

	SALIDA_RM3:
		STS		HRS_UNIDADES, R26
		STS		HRS_DECENAS, R25
		CLR		BANDERA_RESTA
		RET

//Sumar en modo mes
SUMAR_M4:
	LDS     R26, MES_UNIDADES
	LDS		R25, MES_DECENAS 
    INC     R26
	CPI		R26, 3
	BREQ	CONFIRMAR_AUMENTO_M4
	CPI     R26, 10 //Comparar con 10 para aumentar decenas
    BRNE    SALIDA_SM4
	CLR     R26
	STS		MES_UNIDADES, R26

	INC		R25
	STS		MES_DECENAS, R25
	RJMP	SALIDA_SM4

	CONFIRMAR_AUMENTO_M4:
		CPI R25, 1
		BRNE SALIDA_SM4
		LDI R26, 1
		CLR R25

		SALIDA_SM4:
			STS		MES_UNIDADES, R26
			STS		MES_DECENAS, R25
			CLR		BANDERA_SUMA
			RET

//Restar en modo mes
RESTAR_M4:
	LDS R26, MES_UNIDADES
	LDS  R25, MES_DECENAS
	CPI	 R26, 1
	BREQ REV_DEC_M4
	DEC  R26
	RJMP SALIDA_RM4
	
	REV_DEC_M4:
		CPI  R25, 0
		BREQ PEDIR_PRESTADO_M4
		LDI R26, 9
		DEC R25
		RJMP SALIDA_RM4
 
	PEDIR_PRESTADO_M4:
		LDI  R26, 2
		LDI  R25, 1
		RJMP SALIDA_RM4

	SALIDA_RM4:
		STS		MES_UNIDADES, R26
		STS		MES_DECENAS, R25
		CLR		BANDERA_RESTA
		RET

SUMAR_M5:
	LDS		R26, MES_UNIDADES
	LDS		R25, MES_DECENAS
	CPI		R25, 1
	BRNE	PRIMEROS_9_MES_SUMA
	CPI		R26, 0
	BREQ	SUMAR_MES_31
	CPI		R26, 1
	BREQ	SUMAR_MES_30
	CPI		R26, 2
	BREQ	SUMAR_MES_31


	PRIMEROS_9_MES_SUMA:
	CPI		R26, 1
	BREQ	SUMAR_MES_31
	CPI		R26, 2
	BREQ	CONTINUAR_SUMAR_MES28
	CPI		R26, 3
	BREQ	SUMAR_MES_31
	CPI		R26, 4
	BREQ	SUMAR_MES_30
	CPI		R26, 5
	BREQ	SUMAR_MES_31
	CPI		R26, 6
	BREQ	SUMAR_MES_30
	CPI		R26, 7
	BREQ	SUMAR_MES_31
	CPI		R26, 8
	BREQ	SUMAR_MES_31
	CPI		R26, 9
	BREQ	SUMAR_MES_30

	CONTINUAR_SUMAR_MES28:
		RJMP SUMAR_MES_28

	SUMAR_MES_30:
		LDS     R26, DIAS_UNIDADES
		LDS		R25, DIAS_DECENAS 
		INC     R26
		CPI		R26, 1
		BREQ	CONFIRMAR_AUMENTO_MES30_M5
		CPI     R26, 10 //Comparar con 10 para aumentar decenas
		BRNE    CONTINUAR_SALIDA_M5
		CLR     R26
		STS		DIAS_UNIDADES, R26

		INC		R25
		STS		DIAS_DECENAS, R25
		RJMP	SALIDA_SM5

		CONTINUAR_SALIDA_M5:
			RJMP SALIDA_SM5

		CONFIRMAR_AUMENTO_MES30_M5:
			CPI R25, 3
			BRNE SALIDA_SM5
			LDI R26, 1
			CLR R25
			RJMP SALIDA_SM5

	SUMAR_MES_31:
		LDS     R26, DIAS_UNIDADES
		LDS		R25, DIAS_DECENAS 
		INC     R26
		CPI		R26, 2
		BREQ	CONFIRMAR_AUMENTO_MES31_M5
		CPI     R26, 10 //Comparar con 10 para aumentar decenas
		BRNE    SALIDA_SM5
		CLR     R26
		STS		DIAS_UNIDADES, R26

		INC		R25
		STS		DIAS_DECENAS, R25
		RJMP	SALIDA_SM5

		CONFIRMAR_AUMENTO_MES31_M5:
			CPI R25, 3
			BRNE SALIDA_SM5
			LDI R26, 1
			CLR R25
			RJMP SALIDA_SM5

	SUMAR_MES_28:
		LDS     R26, DIAS_UNIDADES
		LDS		R25, DIAS_DECENAS 
		INC     R26
		CPI		R26, 9
		BREQ	CONFIRMAR_AUMENTO_MES28_M5
		CPI     R26, 10 //Comparar con 10 para aumentar decenas
		BRNE    SALIDA_SM5
		CLR     R26
		STS		DIAS_UNIDADES, R26

		INC		R25
		STS		DIAS_DECENAS, R25
		RJMP	SALIDA_SM5

		CONFIRMAR_AUMENTO_MES28_M5:
			CPI R25, 2
			BRNE SALIDA_SM5
			LDI R26, 1
			CLR R25

		SALIDA_SM5:
			STS		DIAS_UNIDADES, R26
			STS		DIAS_DECENAS, R25
			CLR		BANDERA_SUMA
			RET

RESTAR_M5:
	LDS		R26, MES_UNIDADES
	LDS		R25, MES_DECENAS
	CPI		R25, 1
	BRNE	PRIMEROS_9_MES_REST
	CPI		R26, 0
	BREQ	RESTAR_MES_31
	CPI		R26, 1
	BREQ	RESTAR_MES_30
	CPI		R26, 2
	BREQ	RESTAR_MES_31


	PRIMEROS_9_MES_REST:
		CPI		R26, 1
		BREQ	RESTAR_MES_31
		CPI		R26, 2
		BREQ	RESTAR_MES_28
		CPI		R26, 3
		BREQ	RESTAR_MES_31
		CPI		R26, 4
		BREQ	RESTAR_MES_30
		CPI		R26, 5
		BREQ	RESTAR_MES_31
		CPI		R26, 6
		BREQ	RESTAR_MES_30
		CPI		R26, 7
		BREQ	RESTAR_MES_31
		CPI		R26, 8
		BREQ	RESTAR_MES_31
		CPI		R26, 9
		BREQ	RESTAR_MES_30

	RESTAR_MES_30:
		LDS R26, DIAS_UNIDADES
		LDS  R25, DIAS_DECENAS
		CPI	 R26, 1
		BREQ REV_DEC_M5_MES30
		DEC  R26
		RJMP SALIDA_RM5
	
		REV_DEC_M5_MES30:
			CPI  R25, 0
			BREQ PEDIR_PRESTADO_M5_MES30
			LDI R26, 9
			DEC R25
			RJMP SALIDA_RM5
 
		PEDIR_PRESTADO_M5_MES30:
			LDI  R26, 0
			LDI  R25, 3
			RJMP SALIDA_RM5

	RESTAR_MES_31:
		LDS R26, DIAS_UNIDADES
		LDS  R25, DIAS_DECENAS
		CPI	 R26, 1
		BREQ REV_DEC_M5_MES31
		DEC  R26
		RJMP SALIDA_RM5
	
		REV_DEC_M5_MES31:
			CPI  R25, 0
			BREQ PEDIR_PRESTADO_M5_MES31
			LDI R26, 9
			DEC R25
			RJMP SALIDA_RM5
 
		PEDIR_PRESTADO_M5_MES31:
			LDI  R26, 1
			LDI  R25, 3
			RJMP SALIDA_RM5

	RESTAR_MES_28:
		LDS R26, DIAS_UNIDADES
		LDS  R25, DIAS_DECENAS
		CPI	 R26, 1
		BREQ REV_DEC_M5_MES28
		DEC  R26
		RJMP SALIDA_RM5
	
		REV_DEC_M5_MES28:
			CPI  R25, 0
			BREQ PEDIR_PRESTADO_M5_MES28
			LDI R26, 9
			DEC R25
			RJMP SALIDA_RM5
 
		PEDIR_PRESTADO_M5_MES28:
			LDI  R26, 8
			LDI  R25, 2
			RJMP SALIDA_RM5

	SALIDA_RM5:
		STS		DIAS_UNIDADES, R26
		STS		DIAS_DECENAS, R25
		CLR		BANDERA_RESTA
		RET

SUMAR_M6:
	LDS     R26, MIN_UNIDADES_ALM
	LDS		R25, MIN_DECENAS_ALM
    INC     R26
	CPI     R26, 10 //Comparar con 10 para aumentar decenas
    BRNE    SALIDA_SM6
	CLR     R26
	STS		MIN_UNIDADES_ALM, R26

	INC		R25
	STS		MIN_DECENAS_ALM, R25
    CPI     R25, 6 //Comparar con 6 para aumentar la hora
    BRLO    SALIDA_SM6
	CLR     R25
	STS		MIN_DECENAS_ALM, R25
	RJMP	SALIDA_SM6

	SALIDA_SM6:
		STS		MIN_UNIDADES_ALM, R26
		STS		MIN_DECENAS_ALM, R25
		CLR		BANDERA_SUMA
		RET

RESTAR_M6:
	LDS	 R26, MIN_UNIDADES_ALM
	LDS  R25, MIN_DECENAS_ALM
	CPI	 R26, 0
	BREQ REV_DEC_M6
	DEC  R26
	RJMP SALIDA_RM6
	
	REV_DEC_M6:
		CPI  R25, 0
		BREQ PEDIR_PRESTADO_M6
		LDI R26, 9
		DEC R25
		RJMP SALIDA_RM6
 
	PEDIR_PRESTADO_M6:
		LDI  R26, 9
		LDI  R25, 5
		RJMP SALIDA_RM6

	SALIDA_RM6:
		STS  MIN_UNIDADES_ALM, R26
		STS  MIN_DECENAS_ALM, R25
		CLR  BANDERA_RESTA
		RET

SUMAR_M7:
	LDS     R26, HRS_UNIDADES_ALM
	LDS		R25, HRS_DECENAS_ALM
    INC     R26
	CPI		R26, 4
	BREQ	CONFIRMAR_AUMENTO_M7
	CPI     R26, 10 //Comparar con 10 para aumentar decenas
    BRNE    SALIDA_SM7
	CLR     R26
	STS		HRS_UNIDADES_ALM, R26

	INC		R25
	STS		HRS_DECENAS_ALM, R25
	RJMP	SALIDA_SM3

	CONFIRMAR_AUMENTO_M7:
		CPI R25, 2
		BRNE SALIDA_SM7
		CLR R26
		CLR R25
		STS HRS_UNIDADES_ALM, R26
		STS HRS_DECENAS_ALM, R26

	SALIDA_SM7:
		STS		HRS_UNIDADES_ALM, R26
		STS		HRS_DECENAS_ALM, R25
		CLR		BANDERA_SUMA
		RET

RESTAR_M7:
	LDS  R26, HRS_UNIDADES_ALM
	LDS  R25, HRS_DECENAS_ALM
	CPI	 R26, 0
	BREQ REV_DEC_M7
	DEC  R26
	RJMP SALIDA_RM7
	
	REV_DEC_M7:
		CPI  R25, 0
		BREQ PEDIR_PRESTADO_M7
		LDI R26, 9
		DEC R25
		RJMP SALIDA_RM7
 
	PEDIR_PRESTADO_M7:
		LDI  R26, 3
		LDI  R25, 2
		RJMP SALIDA_RM7

	SALIDA_RM7:
		STS		HRS_UNIDADES_ALM, R26
		STS		HRS_DECENAS_ALM, R25
		CLR		BANDERA_RESTA
		RET

COMPARAR_ALM:
	LDS R21, MIN_UNIDADES
	LDS R22, MIN_UNIDADES_ALM
	CP R21, R22
	BRNE SALIDA_ALM

	LDS R21, MIN_DECENAS
	LDS R22, MIN_DECENAS_ALM
	CP R21, R22
	BRNE SALIDA_ALM

	LDS R21, HRS_UNIDADES
	LDS R22, HRS_UNIDADES_ALM
	CP R21, R22
	BRNE SALIDA_ALM

	LDS R21, HRS_DECENAS
	LDS R22, HRS_DECENAS_ALM
	CP R21, R22
	BRNE SALIDA_ALM

	SONAR_ALARMA:
		SBRC R29,0        ; si ya estaba activa, salir
		RET
		
		SBR R29,(1<<0)    ; activar bandera alarma
		SBI PORTB,PORTB4  ; encender buzzer
		RET
	
	SALIDA_ALM:
		CBR R29, (1 << 0)|(1 << 1)
		CBI PORTB, PORTB4
		RET

/****************************************/
// Interrupt routines
PC_ISR:
	PUSH R16
    PUSH R17
    IN   R16, SREG
    PUSH R16

    IN   R16, PINC //Estado actual 
    LDS  R17, ESTADO_ANT //Estado anterior
    EOR  R17, R16

    STS  ESTADO_ANT, R16 //Nuevo estado
    SBRS R17, 0
    RJMP CHECK_PC1
    SBRC R16, 0
	RJMP SALIDA_ISR
    INC MODO
	CPI MODO, MAX_MODOS
	BRLO SALIDA_ISR
	CLR MODO
	RJMP SALIDA_ISR
	
	CHECK_PC1:
		SBRS R17, 1
		RJMP CHECK_PC2
		SBRS R16, 1
		RJMP APAGAR_ALM
		RJMP SALIDA_ISR

		APAGAR_ALM:
			LDI BANDERA_SUMA, 1
			CBI PORTB,PORTB4
			SBR R29,(1 << 0)
			RJMP SALIDA_ISR

	CHECK_PC2:
		SBRS R17, 2
		RJMP SALIDA_ISR
		SBRS R16, 2
		LDI BANDERA_RESTA, 1

	SALIDA_ISR:
		POP  R16
		OUT  SREG, R16
		POP  R17
		POP  R16
		RETI

TMR0_ISR:
	/*PUSH	R16
	IN		R16, SREG
	PUSH	R16

	LDI R16, T0VALUE
	STS TCNT0, R16

	POP R16
	OUT SREG, R16
	POP R16*/
	RETI

TMR1_ISR:
    PUSH    R16
    PUSH    R21
    PUSH    R22
    IN      R16, SREG
    PUSH    R16

    //Recargar el valor del timer1
    LDI     R16, HIGH(T1VALUE)
    STS     TCNT1H, R16
    LDI     R16, LOW(T1VALUE)
    STS     TCNT1L, R16

    LDS     R21, MIN_UNIDADES
    INC     R21
    CPI     R21, 10 //Comparar con 10 para aumentar decenas
    BRLO    GUARDAR_MIN_UNI
    CLR     R21
    STS     MIN_UNIDADES, R21

    LDS     R21, MIN_DECENAS
    INC     R21
    CPI     R21, 6 //Comparar con 6 para aumentar la hora
    BRLO    GUARDAR_MIN_DEC
    CLR     R21
    STS     MIN_DECENAS, R21

    LDS     R21, HRS_UNIDADES
    INC     R21
    CPI     R21, 10 //Comparar con 10 para aumentar las decenas de hora
    BRLO    GUARDAR_HRS_UNI
    CLR     R21
    STS     HRS_UNIDADES, R21

    LDS     R21, HRS_DECENAS
    INC     R21
    STS     HRS_DECENAS, R21
    RJMP    VERIFICAR_24H

	GUARDAR_HRS_UNI:
		STS     HRS_UNIDADES, R21
		RJMP    VERIFICAR_24H

	VERIFICAR_24H:
		//Comprobar el 24
		LDS     R21, HRS_DECENAS
		CPI     R21, 2
		BRNE    SALIDA_TMR1_ISR

		LDS     R21, HRS_UNIDADES
		CPI     R21, 4
		BRNE    SALIDA_TMR1_ISR

		CLR     R21
		STS     HRS_UNIDADES, R21
		STS     HRS_DECENAS, R21
		
		LDS     R22, BANDERAS
		ORI     R22, 0b00000001
		STS     BANDERAS, R22
		RJMP    SALIDA_TMR1_ISR

	GUARDAR_MIN_DEC:
		STS     MIN_DECENAS, R21
		RJMP    SALIDA_TMR1_ISR

	GUARDAR_MIN_UNI:
		STS     MIN_UNIDADES, R21

SALIDA_TMR1_ISR:
    POP     R16
    OUT     SREG, R16
    POP     R22
    POP     R21
    POP     R16
    RETI

TMR2_ISR:
	PUSH R16
    IN   R16, SREG
    PUSH R16

	LDI  R16, T2VALUE //Hacer que el timer empiece en el mismo valor
    STS  TCNT2, R16

	INC R23
	CPI R23, 10
	BRNE SALIDA_TMR2
	SBI PIND, PIND7

	SALIDA_TMR2:
	POP R16
    OUT SREG, R16
    POP R16
    RETI

/****************************************/